name: Lib Java

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'adopt'
        java-version: '17'

    - name: Setup Maven Settings
      run: |
        echo "<settings>
                <servers>
                  <server>
                    <id>github</id>
                    <username>${{ secrets.G_USER }}</username>
                    <password>${{ secrets.G_TOKEN }}</password>
                  </server>
                </servers>
                <mirrors>
                  <mirror>
                    <id>nexus</id>
                    <mirrorOf>central</mirrorOf>
                    <url>https://maven.pkg.github.com/juliobsilva/lab-lib-java-maven</url>
                  </mirror>
                  <mirror>
                    <id>central</id>
                    <mirrorOf>central</mirrorOf>
                    <url>https://repo.maven.apache.org/maven2</url>
                  </mirror>
                </mirrors>
              </settings>" > $HOME/.m2/settings.xml

    - name: Build artifact
      run: mvn clean verify -Drelease=true -Dmaven.source.skip=true -f pom.xml

    - name: Get package name
      id: package-name
      run: echo "::set-output name=package::$(mvn -q -Dexec.executable=echo -Dexec.args='${project.build.finalName}' --non-recursive exec:exec)"

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.package-name.outputs.package }}
        path: ./target/${{ steps.package-name.outputs.package }}*.jar
        retention-days: 7

    - name: List files
      run: ls -l ./target

    - name: Upload Package to Nexus
      run: mvn clean deploy -Drelease=true -Dmaven.source.skip=true -Dmaven.test.skip=true -s $HOME/.m2/settings.xml -f pom.xml

    - name: Build with Maven
      run: mvn clean install
