name: Lib Java

on:
    push

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Set up JDK
          uses: actions/setup-java@v4
          with:
            distribution: 'adopt'
            java-version: '17'

        - name: Build with Maven
          run: mvn clean install

        - name: Upload to Nexus
          run: mvn deploy -DaltDeploymentRepository=${{github.repository}}::default::${{ env.NEXUS_URL }}
          env:
                NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
                NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
                NEXUS_URL:      ${{ secrets.NEXUS_URL }}
