name: Lib Java

on:
    push

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Set up JDK
          uses: actions/setup-java@v4
          with:
            distribution: 'adopt'
            java-version: '17'

        - name: Build with Maven
          run: mvn package --file pom.xml

        - name: Nexus Repo Publish
          uses: sonatype-nexus-community/nexus-repo-github-action@master
          with:
            serverUrl: http://172.172.38.150:8081/
            username:  ${{ secrets.NEXUS_USERNAME }}
            password:  ${{ secrets.NEXUS_PASSWORD }}
            format: maven2
            repository: repo-teste
            coordinates: groupId=lab-lib-java-mave.com artifactId=lib-java version=0.0.1-SNAPSHOT
            assets: extension=jar
            filename: ./target/app-1.0.0.jar

        - name: Build with Maven
          run: mvn clean install